### ISSUE TITLE
Create a test runner for small code snippets

### ISSUE THREAD

**Issue by hermanventer** [facebookexperimental/MIRAI#10]
We can expect to accumulate a large collection of small program snippets, each of which exercises some small part of Mirai. It is not convenient to have to write a new entry in tests/integration_tests.rs for each snippet and to have to recompile the ever growing tests/integration_tests.rs every time we add a snippet.

So, instead, let's write a dedicated test runner that will invoke mirai independently on each snippet found in a dedicated directory (e.g. tests/snippets). There should be a mode that can run a designated snippet for debugging purposes (BTW. I can't figure out how to debug a test run via cargo test with VSCode. Please comment if you know how.)

Preferably a default run should use all of the cores of the machine it is running on and should produce minimal console spew for successful runs. When one or more tests fail, the console output should be no more than is needed to run any of the failing tests as an individual run inside a debugger.

**Comment by fpoli** [comment]
An interesting crate to look at for this is compiletest-rs, which we also use in Prusti. It can be used, for example, to test that the compiler driver emits determined error messages.

(Sorry for not providing more links, I'm from the mobile)

**Comment by hermanventer** [comment]
This sounds like just the thing to use.

**Comment by hermanventer** [comment]
I spent some more time looking into the possibility of leveraging compiletest-rs and the underlying logic in the rustc compiler, while not creating a new process for every test run. So far, I have not come across a simple way to reuse code from these sources, partly because so much of it is not public.
