### ISSUE TITLE
Debug MIRAI in CLion

### ISSUE THREAD

**Issue by ortem** [facebookexperimental/MIRAI#107]
Hi everyone! I've just heard about MIRAI. The project is very exciting and I hope it will eventually become a part of IntelliJ Rust and RLS code analysis! However, while reading the documentation I was surprised to see that CLion doesn't support debugging MIRAI ([[1]](https://github.com/facebookexperimental/MIRAI/blob/master/documentation/DeveloperGuide.md#debugging) and [[2]](https://github.com/facebookexperimental/MIRAI/blob/master/documentation/DebuggingRustc.md)).

I've just tried it out and seems like it works fine:
<img width="992" alt="Screenshot 2019-03-30 at 12 21 02" src="https://user-images.githubusercontent.com/4854600/55274221-2567e680-52e7-11e9-9bed-5b5160a7b89a.png">

All I have to do is to provide the `DYLD_LIBRARY_PATH` as specified: 
<img width="1185" alt="Screenshot 2019-03-30 at 12 35 29" src="https://user-images.githubusercontent.com/4854600/55274333-5399f600-52e8-11e9-82c1-bac7cd62c589.png">

Also [[3]](https://github.com/facebookexperimental/MIRAI/issues/64#issue-405449900),
> debugging support for Rust is pretty much non existent

I'm sorry to hear that. I'm working on new lldb formatters for Rust; in CLion, they are enabled by default and configurable via `Preferences | Build, Execution, Deployment | Debugger | Data Views | Rust`. I hope debugging support gets better, though there is no `Evaluate expression` for Rust yet. So I really want to know if something related to debugging frontend doesn't work properly or if you have some ideas to improve it (at frontend level, like formatters, watches, remote debugging and so on). If so, you can open an issue [here](https://github.com/intellij-rust/intellij-rust/issues).

**Comment by hermanventer** [comment]
The CLion debugger does indeed work now and I use it all of the time. Rust support in Clion has improved with leaps and bounds in the last few months and I could not be happier about it. I'll update the MIRAI documentation to reflect this.

When it comes to debugging, my single greatest frustration is not being able to view non primitive values. Without that feature I consider any debugger to be close to useless. Beyond that, expression evaluation and conditional breakpoints are the most valuable features for me. And beyond that, if you can match or exceed the gold standard in debuggers, namely the Visual Studio C# debugger, you'll be leading the big league. :-)

**Comment by ortem** [comment]
> my single greatest frustration is not being able to view non primitive values

Is this still relevant for now? CLion [support](https://twitter.com/intellijrust/status/1067725887880126464) formatting some composite values: `String`, `Vec`, `VecDeque` `Rc`, `Arc`, `Ref`, `Cell`, and few others. I'd like to know if there are other important unsupported types (except `HashMap`: currently it is not supported due to one debuginfo issue in rustc).

**Comment by hermanventer** [comment]
Some is certainly better than none, so thanks for added that support. Unfortunately, unless the debugger provides me with a way to look at the fields of an arbitrary structure (or enum) it will never be a real solution. Right now, even if it will just display what `debug!("{:?}", some_struct)` would display it would be a great improvement.

**Comment by ortem** [comment]
@hermanventer  Structures are already supported (if I understand you correctly):
<img width="583" alt="Screenshot 2019-04-01 at 20 41 16" src="https://user-images.githubusercontent.com/4854600/55347889-84cc1f00-54be-11e9-95ee-e875fc55f474.png">

But enums formatting was broken at least since 1.32.0 due to [this](https://github.com/rust-lang/rust/issues/58492) (and I don't know why).

**Comment by hermanventer** [comment]
Magic! I can debug now. Free at last.

**Comment by Undin** [comment]
@hermanventer JFYI since CLion 2020.1 Rust enums are properly rendered while debugging with lldb

**Comment by hermanventer** [comment]
Thanks for the update. I've tried out debugging with the EAP Clion and while I do now see information about enums, I sadly see the wrong information. It seems that the enums I'm looking at are always displayed as if their values were 0, even when that is clearly not the case.

**Comment by ortem** [comment]
@hermanventer Could you please provide more details (exact enum and code you debug)? Enum debugging works fine on my macOS + CLion 2020.1 EAP + 0.2.116 Rust plugin. Thanks in advance!

<img width="1346" alt="Screenshot 2020-02-05 at 19 51 00" src="https://user-images.githubusercontent.com/4854600/73863356-f8625980-4850-11ea-9548-4e03447c4e11.png">

**Comment by hermanventer** [comment]
Debugging is much better now.
