### ISSUE TITLE
failed to run custom build command for `z3-sys v0.7.1`

### ISSUE THREAD

**Issue by EmirVildanov** [facebookexperimental/MIRAI#1152]
## Issue

Failed to execute command
`cargo install --locked --path ./checker`

Console output:
`error: failed to run custom build command for `z3-sys v0.7.1`

Caused by:
  process didn't exit successfully: `<FOLDER>/MIRAI/target/release/build/z3-sys-36e731f90cdfdf70/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=wrapper.h

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', <HOME>/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.58.1/src/lib.rs:2057:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `mirai v1.1.0 (<FOLDER>/MIRAI/checker)`, intermediate artifacts can be found at `<FOLDER>/MIRAI/target`
`

## Steps to Reproduce
1) sudo apt-get install libz3-dev
2) git clone https://github.com/facebookexperimental/MIRAI.git
3) cd MIRAI
4) ./setup.sh
5) cargo install --locked --path ./checker

## Expected Behavior

Installing cargo package
## Actual Results

Panic
## Environment

OS: Ubuntu 20.04.4 LTS
Rust version: rustc 1.61.0-nightly (eb82facb1 2022-04-01)

**Comment by EmirVildanov** [comment]
Managed to solve the issue with command
`sudo apt-get install libclang-dev`

**Comment by hermanventer** [comment]
Thanks for the update. I'll add this solution to the documentation. Since I can no longer merge PRs into this repo, and no-one at Meta seems interested in helping me, please regard https://github.com/hermanventer/MIRAI as the source of truth from now on.
