### ISSUE TITLE
Request of a nightly Rust toolchain update

### ISSUE THREAD

**Issue by hiroki-chen** [facebookexperimental/MIRAI#1188]
## Issue
Currently, MIRAI is using `nightly-2022-09-05` which is a little bit old for our project, and MIRAI cannot be built with the latest nightly toolchain, so we are seeking an update for MIRAI. Is there any plan for it?

**Comment by hermanventer** [comment]
Yes, I am working on it. Unfortunately MIR is very unstable at the moment and a lot of things have been broken lately. I'll check something in tomorrow and keep at it until everything is fixed. I also need MIRAI to keep up to date and to work, so this is important to me. What is the oldest nightly you can tolerate in the next week or so?

**Comment by hiroki-chen** [comment]
@hermanventer Hmm, perhaps `nightly-2022-10-15` or later? We are now using the newest version, i.e., `nightly-2022-10-22`, although I suppose any nightly toolchain containing rustc versioned 1.66.0 would work for us :)
