### ISSUE TITLE
Environment variable MIRAI_FLAGS or MIRAI_LOG do not work

### ISSUE THREAD

**Issue by gfzum** [facebookexperimental/MIRAI#1209]
## Issue

I set environment variables `MIRAI_FLAGS=--diag=verify` or `MIRAI_LOG=debug` in the terminal and run `cargo mirai` under my cargo package, but it didn't work as there was no additonal infomation shown.

## Steps to Reproduce

```
git clone https://github.com/facebookexperimental/MIRAI.git
cd MIRAI
cargo install --locked --path ./checker
```

-  `cd` to any Rust package directory
- do `export MIRAI_LOG=debug` or `MIRAI_LOG=debug` , then `cargo mirai`.
- do `MIRAI_LOG=debug cargo mirai`

## Expected Behavior

Additional debug information is expected to be shown.

## Actual Results

Only basic information:

```
gfzum@gvm:~/cxsj/case2$ MIRAI_LOG=debug cargo mirai
Finished dev [unoptimized + debuginfo] target(s) in 0.14s
```

## Environment

rustc 1.65.0 (897e37553 2022-11-02)
Ubuntu 22.04.1
bash

**Comment by hermanventer** [comment]
Before doing cargo mirai, try cargo clean.

**Comment by gfzum** [comment]
It works! thanks : )
