### ISSUE TITLE
MIRAI fails analysing: error: could not compile <bin>

### ISSUE THREAD

**Issue by YannikCode** [facebookexperimental/MIRAI#1220]
## Issue

I can not compile and check my package. It aborts the compilation process with an error message.
RUST_BACKTRACE did not help getting more information.

## Actual Results

error: could not compile `common`

Caused by:
  process didn't exit successfully: `/home/kali/.cargo/bin/cargo-mirai rustc --crate-name common --edition=2021 common/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=114 --crate-type lib --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 -C metadata=283c6a0d98c90eeb -C extra-filename=-283c6a0d98c90eeb --out-dir /home/kali/Documents/sp-review-crawlertools/src/mc-crawler-tools/target/debug/deps -C incremental=/home/kali/Documents/sp-review-crawlertools/src/mc-crawler-tools/target/debug/incremental -L dependency=/home/kali/Documents/sp-review-crawlertools/src/mc-crawler-tools/target/debug/deps --extern bson=/home/kali/Documents/sp-review-crawlertools/src/mc-crawler-tools/target/debug/deps/libbson-b54f7aee01386898.rmeta --extern chrono=/home/kali/Documents/sp-review-crawlertools/src/mc-crawler-tools/target/debug/deps/libchrono-8e65e2801ae8cf50.rmeta --extern futures=/home/kali/Documents/sp-review-crawlertools/src/mc-crawler-tools/target/debug/deps/libfutures-7e28e038e99a68c6.rmeta --extern log=/home/kali/Documents/sp-review-crawlertools/src/mc-crawler-tools/target/debug/deps/liblog-3f49dd95c301a0aa.rmeta --extern mongodb=/home/kali/Documents/sp-review-crawlertools/src/mc-crawler-tools/target/debug/deps/libmongodb-5f0faef77df4e663.rmeta --extern serde=/home/kali/Documents/sp-review-crawlertools/src/mc-crawler-tools/target/debug/deps/libserde-a0ff42e0249cce64.rmeta --extern serde_json=/home/kali/Documents/sp-review-crawlertools/src/mc-crawler-tools/target/debug/deps/libserde_json-f1c5a04123c06e6e.rmeta --cfg mirai -Z always_encode_mir -L native=/home/kali/Documents/sp-review-crawlertools/src/mc-crawler-tools/target/debug/build/ring-6ac68a7eb947409a/out` (exit status: 255)

## Environment

rustc 1.70.0 (90c541806 2023-05-31)
tried it with stable(stable-x86_64-unknown-linux-gnu) and nightly(nightly-x86_64-unknown-linux-gnu)
OS: Debian

The package itself contains three separate directories. Two of them produce binaries and one, the common directory, provides type definitions and functions to the other projects.
When running MIRAI either at the root of the project or in one of the subdirectories, I am getting this error message. 

I am new to rust and gaining first experience with it by analysing the project tool based for improvements.
Thanks in advance.

**Comment by lometsj** [comment]
Have you resolved this problem?
I have the same error.
@YannikCode

**Comment by YannikCode** [comment]
@lometsj Unfortunally no
