### ISSUE TITLE
feature request: Annotating traits for attaching tags

### ISSUE THREAD

**Issue by mimoo** [facebookexperimental/MIRAI#1224]
Hello hello.

I see that I can detect tags on a trait implementation easily, but I'd like to do the reverse: I'd like to call `add_tag!(&value_to_be_tagged, SecretTaint);` automatically on the output values of a trait method definition (so that any implementors also get their outputs tagged).

Is this possible?

**Comment by mimoo** [comment]
I see that actually, using `#[contract_trait]` doesn't work well with existing libraries that are already being implemented a certain way :c it'd be nice to have a way to insert pre or post conditions on all implementations of a trait method. But I don't see a way to do this yeah...

**Comment by hermanventer** [comment]
I don't think there is an easy way to implement this feature, which means that I also don't think I'll be the one to implement it, if it ever gets implemented.
