### ISSUE TITLE
Memory Usage for rebuild_std.sh

### ISSUE THREAD

**Issue by masapr** [facebookexperimental/MIRAI#1229]
The script `rebuild_std.sh` runs out of memory on my machine (with almost 32GB free RAM). It works fine, when I remove `MIRAI_START_FRESH=true`.

I'm on commit `41b3c946163df3faf543667b64448bd2abc3357f`

**Comment by hermanventer** [comment]
Is this still an issue? I don't see the problem when I run rebuild_std.sh on my much less well endowed laptop. What OS are you running on?

**Comment by masapr** [comment]
I checked again: the problem only occurs on my fork, where we included more dependencies. If I run it from this repository, it actually works. Sorry, I wasn't aware that our code would have any influence on this.

**Comment by masapr** [comment]
@hermanventer if you want to reproduce this issue, you can checkout our [fork on branch Milestone1_Research](https://github.com/scs/MIRAI/tree/Milestone1_Research)
