### ISSUE TITLE
Add JSON structure reporting

### ISSUE THREAD

**Issue by TomMD** [facebookexperimental/MIRAI#1231]
## Issue

Lack of machine parsable (JSON) output makes MIRAI hard to integrate into CI

## Steps to Reproduce

MIRA_FLAGS="--json" cargo mirai

## Expected Behavior

stdout or a specified reports file in JSON

## Actual Results

Unstructured text is the only MIRAI output.

**Comment by hermanventer** [comment]
MIRAI is a plugin for rustc and the latter takes care of emitting the diagnostics. Try RUSTFLAGS="--error-format=json".
