### ISSUE TITLE
[Facebook Internal] Constants are not always recognized in annotations

### ISSUE THREAD

**Issue by darioncassel** [facebookexperimental/MIRAI#201]
## Issue

Constants used in annotations are not always recognized to mean literal value.

## Steps to Reproduce

Please see: https://our.internmc.facebook.com/intern/diff/D15950558/

## Expected Behavior

If a MIRAI annotation contains a constant, the constant should be recognized and its value should be used in the annotation.

## Actual Results

If the value of the constant is substituted into the annotation, then it behaves as expected. If the constant is used, the annotation does not have the desired effect.

## Environment

Rust version (rustc --version): `rustc 1.37.0-nightly (b25ee6449 2019-06-17)`

**Comment by hermanventer** [comment]
The problem is that the constant is defined in another crate which was not summarized prior to analyzing the crate that used the constant.
