### ISSUE TITLE
Contracts for Rust primitives

### ISSUE THREAD

**Issue by darioncassel** [facebookexperimental/MIRAI#210]
## Issue

Currently one cannot write a contract for a Rust primitive such as `str`. 

The format of a contract on a function has to be such that MIRAI recognizes it as the same as the mangled name of the actual function. If the function is for a primitive type, i.e. `str::as_bytes`, then one will need a model of `str`. However, Rust only allows one definition of language builtins.

## Steps to Reproduce

Attempt to use the following contract:
```
pub mod str {
    impl str {
        pub fn len(&self) -> usize {
            self.as_bytes().len()
        }
    }
}
```

## Expected Behavior

One should be able to define an alternate name for language builtins that MIRAI recognizes. For example, `impl rust_builtin_str`. The `rust_builtin` prefix would be stripped by MIRAI.

## Actual Results

Rust does not allow the above contract to be written; it gives the error:
`error[E0390]: only a single inherent implementation marked with '#[lang = "str"]' is allowed for the `str` primitive`

## Environment

Rust version (rustc --version): `rustc 1.37.0-nightly (2fe7b3383 2019-06-19)`

**Comment by hermanventer** [comment]
It seems that it should be OK to just use "pub mod str" rather than "impl str".
