### ISSUE TITLE
Lack of support for bitwise negation

### ISSUE THREAD

**Issue by uraj** [facebookexperimental/MIRAI#228]
## Issue

MIRAI seems to treat all expressions like `!e` as logical negation, while Rust does support bitwise negation operation. This makes Z3 crash due to typing errors.

## Steps to Reproduce

Run MIRAI for the utf8-range crate (v1.0.3) reproduces the crash. More specifically, the crash is triggered when analyzing the function [`Utf8Sequences::next`](https://github.com/BurntSushi/utf8-ranges/blob/eda2c387d1f4368933ebd53b89850bcdf11f1560/src/lib.rs#L334).

## Expected Behavior

The analysis should terminate without errors.

## Actual Results

An error message from Z3 before crash: `Error: Sort mismatch at argument #1 for function (declare-fun not (Bool) Bool) supplied sort is Int`

## Environment

Rust version 1.37.0-nightly (5f3656ce9 2019-06-11)

**Comment by uraj** [comment]
The bug can be fixed either by introducing a new `Expression` member `BitNot`, or by looking at the type of the subexpression to differentiate the overloading cases. I have a patch for the latter case. It seems to fix the bug.

**Comment by hermanventer** [comment]
Thanks for the bug report. I would be very happy to look at your patch if you care to make a pull request for it.

**Comment by uraj** [comment]
I'm preparing a pull request. However, I'm having difficulties in passing one of my own tests. My current guess is that since the abstract domain extends everything into 128-bit bitvectors, adding bitwise negation for unsigned integers requires additional effort to make the algebra right.

**Comment by hermanventer** [comment]
Yes, if ! can result in something other than a bool, the operation will have to track size of the result, much like overflow operations do.

I've just run into this issue myself and I'm busy taking a look at it now.

**Comment by uraj** [comment]
It seems that `U128` and `I128` of `ConstantDomain` have to memorize the original size of the literal. Or `ConstantDomain` has to be extended to precisely present integers of different sizes. Either way, it's going to be a breaking change. But I just started looking at the code yesterday so maybe there is a better way to do it.

**Comment by hermanventer** [comment]
I think I have something that will work.
