### ISSUE TITLE
MIRAI reports a false warning with verify!

### ISSUE THREAD

**Issue by t-rasmud** [facebookexperimental/MIRAI#265]
## Issue

MIRAI issues a false warning when a provably true condition is specified with `verify!`

## Steps to Reproduce
Test case:
```
use mirai_annotations::{verify};
use std::{
    sync::Arc,
};

pub type Round = u64;

pub struct Block
{
    round: Round,
}

impl Block
{
    pub fn round(& self) -> Round {
        let result = self.round;
        result
    }

    pub fn voting_rule(
        &mut self,
        proposed_block: Arc<Block>,
    )  {
        if proposed_block.round() <= self.round() {
            return;
        }
        verify!(proposed_block.round() > self.round());
    }
}
```

## Expected Behavior

No MIRAI warning.

## Actual Results

```
warning: possible false verification condition
  --> src/lib.rs:27:9
   |
27 |         verify!(proposed_block.round() > self.round());
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this warning originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

## Environment

Rust version (rustc --version): `rustc 1.38.0-nightly (6e310f2ab 2019-07-07)`

**Comment by hermanventer** [comment]
What is happening here is that there are no summaries for Arc, hence proposed_block.round() is an uninterpreted function call. Although we constrain the result of the first call to round, we cannot use that to reason about the result of the second call to round.
