### ISSUE TITLE
Decide on command line options for Mirai

### ISSUE THREAD

**Issue by hermanventer** [facebookexperimental/MIRAI#3]
Talk to potential users of Mirai and determine if there is any need for Mirai specific build options.

Also determine if Mirai should automatically add options to the list it passes to the Rust compiler, for example in order to make the compilation produce additional information that will help static analysis.

**Comment by hermanventer** [comment]
We need at least one option: -db/--summary-db path. This will specify where to create the RocksDB directory in which function summaries will be stored.

**Comment by sanxiyn** [comment]
Consider using [lint plugin](https://doc.rust-lang.org/unstable-book/language-features/plugin.html#lint-plugins) interface like Clippy instead of rustc_driver interface. Rust people are already familiar with Clippy.

**Comment by hermanventer** [comment]
MIRAI depends on analyzing Mid level Intermediate Representation (MIR). Last time I checked I did not get the impression that MIR is available via the lint plugin interface.

**Comment by sanxiyn** [comment]
You may want to [check again](https://github.com/rust-lang/rust-clippy/blob/61aa5c957c219abe1fb2d1b5e51db8b365b4f565/clippy_lints/src/missing_const_for_fn.rs#L105). :)

**Comment by hermanventer** [comment]
Nice, thanks for the heads up. I won't be able to do anything about it myself in the next few months. Any related PRs from other contributors will be carefully and gratefully considered.

**Comment by hermanventer** [comment]
At the moment it looks as if any command line switch we may want for MIRAI could just as well be specified via an environmental variable. Closing this until it becomes clear it is actually needed.
