### ISSUE TITLE
Cross module and cross crate analysis

### ISSUE THREAD

**Issue by ilovepi** [facebookexperimental/MIRAI#303]
## Issue

I've been experimenting with MIRAI, and have noticed that if I use instrumented APIs in another module, I don't get any warnings about precondition violations.

I also experimented with adding MIRAI preconditions in an external crate, and saw a similar lack of diagnostics.

Is this a known limitation? Did I miss something in MIRAI's documentation? Is this functionality still in the development?

Ultimately, I'd like to perform taint analysis across an entire project, which seems in scope for MIRAI, unless I'm mistaken.

## Steps to Reproduce
src/main.rs
```
extern crate untrusted;
use std::sync::Arc;
use untrusted::{source, use_arc, Foo};
fn use_arc_test() {
    let foo: Foo = source(Arc::new([1, 2, 3])); // get tainted foo
    let (_, sum) = use_arc(foo); // use tainted foo
    println!("sum = {}", sum);
}

fn main() {
    use_arc_test();
}
```

untrusted/src/lib.rs
```
#[macro_use]
extern crate mirai_annotations;

use std::sync::Arc;

pub struct Foo {
    pub arc: Arc<[i32]>,
}

pub fn source(arc: Arc<[i32]>) -> Foo {
    let result = Foo { arc: arc };
    set_model_field!(&result, tainted, true);
    result
}

pub fn use_arc(foo: Foo) -> (Arc<[i32]>, i32) {
    precondition!(!get_model_field!(&foo, tainted, false));
    let sum: i32 = foo.arc.iter().sum();
    unsafe {
        let arc_array = foo.arc;
        let ptr = Arc::into_raw(arc_array);
        (Arc::from_raw(ptr), sum)
    }
}
```

Build a project that uses untrusted/src/lib.rs as an external dependency using MIRAI(slight modifications for a mod also seem to work).

## Expected Behavior

Expected a MIRAI warning about an invalid precondition
```
warning: unsatisfied precondition
  --> src/lib.rs:
   |
   |         use_arc(tainted); //~ unsatisfied precondition
   |         ^^^^^^^^^^^^^^^^
   |
```

## Actual Results

No diagnostics appear

## Environment

Rust version (rustc --version)

rustc 1.39.0-nightly (f0b58fcf0 2019-09-11)

**Comment by hermanventer** [comment]
I'm able to reproduce this. It is due to a recent change that relies on the Rust compiler to provide the MIR for out of crate functions. For some reason, in case like this, the compiler does not provide MIR.

I'll see what I can do about this. Meanwhile you can use the MIRAI_SHARE_PERSISTENT_STORE flag:

```
hermanv-mbp:taint_bug hermanv$ RUSTC_WRAPPER=mirai MIRAI_SHARE_PERSISTENT_STORE=true cargo build
   Compiling mirai-annotations v1.4.0
   Compiling untrusted v0.1.0 (/Users/hermanv/CLionProjects/taint_bug/untrusted)
   Compiling taint_bug v0.1.0 (/Users/hermanv/CLionProjects/taint_bug)
warning: unsatisfied precondition
  --> src/main.rs:11:5
   |
11 |     use_arc_test();
   |     ^^^^^^^^^^^^^^
   |
note: related location
  --> src/main.rs:6:20
   |
6  |     let (_, sum) = use_arc(foo); // use tainted foo
   |                    ^^^^^^^^^^^^

    Finished dev [unoptimized + debuginfo] target(s) in 0.68s

```
