### ISSUE TITLE
MIRAI not able to silence itself

### ISSUE THREAD

**Issue by mimoo** [facebookexperimental/MIRAI#321]
## Issue

Running MIRAI on Libra, specifically the `storage/accumulator` crate, and I'm running into a false positive that is surprising. [The problem seems to be here](https://github.com/libra/libra/blob/89323bf9cc762b03579be91a41eb6f45230c0e03/storage/accumulator/src/lib.rs#L294) and is a potential underflow. 

```
    fn rightmost_leaf_index(&self) -> u64 {
        (self.num_leaves - 1) as u64
    }
```

Investigating:
* `rightmost_leaf_index` is private, so it's easy to investigate (it's only called from this file).
* `rightmost_leaf_index` is only called by a private `get_hash(&self, ...)` function that takes a non-mutable self (so cannot change the value of `num_leaves`).
* all call sites of `get_hash()` do check that the value cannot be 0:

```
if self.num_leaves == 0 {
                return Ok((*ACCUMULATOR_PLACEHOLDER_HASH, Vec::new()));
            } else {
               // ...
            }
```

and

```
ensure!(
            leaf_index < self.num_leaves as u64,
            "invalid leaf_index {}, num_leaves {}",
            leaf_index,
            self.num_leaves
        );
// ...
```

## Steps to Reproduce

* run MIRAI in `storage/accumulator`

## Expected Behavior

MIRAI should not complain 

## Actual Results

```
warning: possible attempt to subtract with overflow
   --> storage/accumulator/src/lib.rs:327:22
    |
327 |             .map(|p| self.get_hash(p))
    |                      ^^^^^^^^^^^^^^^^
    |
note: related location
   --> storage/accumulator/src/lib.rs:298:19
    |
294 |         (self.num_leaves - 1) as u64
    |         ^^^^^^^^^^^^^^^^^^^^^
...
298 |         let idx = self.rightmost_leaf_index();
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Environment

rustc 1.40.0-nightly (2daa404e9 2019-10-02)

**Comment by hermanventer** [comment]
The fact that the offending call lives inside a closure and the closure is invoked via a map makes this analysis a lot more difficult than it may seem. I'm working on this problem, but it will be quite a while before something like this can be expected to work reliably.

**Comment by hermanventer** [comment]
Things will be silent by default now because of the extended Angelic behavior.
