### ISSUE TITLE
Outdated cargo installation step

### ISSUE THREAD

**Issue by disconnect3d** [facebookexperimental/MIRAI#361]
## Issue

The installation step present in https://github.com/facebookexperimental/MIRAI/blob/master/documentation/InstallationGuide.md#installing-mirai-into-cargo does not work:
```
$ cargo install --git https://github.com/facebookexperimental/MIRAI

    Updating git repository `https://github.com/facebookexperimental/MIRAI`
error: multiple packages with binaries found: mirai, shopping_cart, taint
```

## Environment

This happens on MacOS and rustc installed via `rustup override set <proper  version>` or:
```
$ rustc --version
rustc 1.41.0-nightly (ded5ee001 2019-11-13)
```

**Comment by hermanventer** [comment]
`cargo install --git https://github.com/facebookexperimental/MIRAI --bin mirai` might do the trick. I'll test and update the documentation when I get a chance.

**Comment by hermanventer** [comment]
`cargo install --git https://github.com/facebookexperimental/MIRAI mirai --force`
