### ISSUE TITLE
Simple assertions not failing as expected

### ISSUE THREAD

**Issue by zvonimir** [facebookexperimental/MIRAI#389]
## Issue

I have been working on porting SMACK Rust regressions to MIRAI to uncover potential issues. The eventual goal is to have a nice publicly available suite of Rust benchmarks.
Along the way I discovered this MIRAI issues, where it appears to be missing the fact that the two assertions in this small example should obviously fail.

## Steps to Reproduce

Run MIRAI on this small example:
```
#[macro_use]
extern crate mirai_annotations;

pub fn main() {
  let a : i32 = result!();
  let b : i32 = result!();
  assume!(4 < a && a < 8); // a in [5,7]
  assume!(5 < b && b < 9); // b in [6,8]
  verify!(36 <= a * b); // a*b in [30,56]
  verify!(a * b <= 49); // a*b in [30,56]
}
```

## Expected Behavior

Both assertions should fail.

## Actual Results

The assertions are not failing.

## Environment

rustc 1.42.0-nightly (0de96d37f 2019-12-19)
MIRAI v1.0.5

**Comment by hermanventer** [comment]
Both calls to result!() produce the same abstract value (local_0 in MIR), so the assumptions are contradictory and anything goes. This would be the test case for introducing a new way to specify an abstract value that is not meant to be the result of a function.

**Comment by zvonimir** [comment]
Ah, I see. They are not quite contradictory since there is an overlap between the intervals they constrain. Bug this explains the weird outcomes I've been observing.

**Comment by zvonimir** [comment]
I created a more general discussion to resolve this in #397. It would be good to reach some kind of an agreement there.
Related this this particular issue, I am used to functions like `result!` creating a fresh abstract value with every invocation. That is how verifiers that I am familiar with operate at least.
