### ISSUE TITLE
Discussing format for Rust verification benchmarks

### ISSUE THREAD

**Issue by zvonimir** [facebookexperimental/MIRAI#397]
So as we discussed, I've been working on putting together a nice suite of Rust verification benchmarks. I think this would benefit everyone working on this area.

To be able to do this, we should discuss the format we would like to use for common verifier primitives. My goal has been to roughly match the SVCOMP style for doing this (https://sv-comp.sosy-lab.org/) since hopefully one day these benchmarks would get merged into the SVCOMP repo (and we would potentially have a Rust verification competition).

We need support for 3 basic things from a verifier to be able to create such a suite: assertions, assumptions, and nondeterministic (abstract, symbolic) values. See 

In the case of Rust, assertions and assumptions are easy since we can simply leverage `assert!` and `assume!` macros. So that is all good.

Now, nondet values are slightly more complicated.
This is how we do it in SMACK, which pretty well matches the SVCOMP style:
```
fn main() {
  let a = 6i32.verifier_nondet();
  let b = 7i32.verifier_nondet();
  assume!(4 < a && a < 8); // a in [5,7]
  assume!(5 < b && b < 9); // b in [6,8]
  assert!(30 <= a * b && a * b <= 56); // a*b in [30,56]
}
```

And this is how it is implemented under the hood:
https://github.com/smackers/smack/blob/update-rust-nondet/share/smack/lib/smack.rs#L53

I could imagine implementing something similar for MIRAI, but one functionality that is currently missing is to be able to introduce different nondeterministic (abstract, symbolic) values. I thought that `result!` achieves that, but that is not quite the case.

We are also not set on the above style/format, and that is open to discussion as well. However, it would be good to agree on this so that we could have a common benchmark suite that can be easily processed by both tools (and hopefully others too).

**Comment by hermanventer** [comment]
Actually, we can't leverage assert! since that is a standard Rust annotation that is often used to indicate a precondition.

The MIRAI way is to use verify! for conditions that the verifier should check.

**Comment by zvonimir** [comment]
I see. So I thought a bit more about this. Would you be ok to rename `assume` as `verifier_assume` and `verify` as `verifier_assert`?
Alternatively, we could introduce `verifier_assume` and `verifier_assert` in addition to what is already there in MIRAI, as an alternative way to specify assumes and asserts.

**Comment by hermanventer** [comment]
I'm not falling over myself to make breaking API changes. Perhaps we can discuss this in person.

**Comment by zvonimir** [comment]
Sure, your call.
