### ISSUE TITLE
False bug reported when resizing vectors

### ISSUE THREAD

**Issue by zvonimir** [facebookexperimental/MIRAI#435]
## Issue

MIRAI reports a false bug.

## Steps to Reproduce

Run MIRAI on the following code:
```
#[macro_use]
extern crate mirai_annotations;

pub fn main() {
    let mut v1: Vec<u64> = vec![0];
    let mut v2: Vec<u64> = vec![3];
    v1.append(&mut v2);
    verify!(v1[1] == 3);
}
```

## Expected Behavior

The program contains no bugs, and yet MIRAI reports a possibly false verification condition.

## Environment

MIRAI v1.0.5rustc 1.42.0-nightly (9ed29b6ff 2020-01-29)

**Comment by zvonimir** [comment]
Even this example has similar problems:
```
pub fn main() {
    let mut v: Vec<u64> = Vec::new();
    v.push(0);
    v.push(1);
    v.push(3);
    verify!(v[0] == 0);
    verify!(v[1] == 1);
    verify!(v[2] == 3);
    v[2] = v[0] + v[1];
    verify!(v[0] == 0);
    verify!(v[1] == 1);
    verify!(v[2] == 1);
}
```

**Comment by hermanventer** [comment]
Supporting vectors is still a work in progress. It will probably take another week or two.

**Comment by hermanventer** [comment]
Even something as simple looking as a call to push becomes low level pointer manipulation. Support for that has been improving but it is not quite all there yet. Putting this off some more while looking at other problems.

**Comment by hermanventer** [comment]
The false positive in the first example is beyond MIRAI in v1 because it involves loops and there is currently no loop unrolling. Consequently, the state of v1[1] becomes abstract after the call to append and the equality with 3 cannot be proved.
