### ISSUE TITLE
False bug reported in the presence of options

### ISSUE THREAD

**Issue by zvonimir** [facebookexperimental/MIRAI#436]
## Issue

MIRAI reports a false bug in the presence of options.

## Steps to Reproduce

Run MIRAI on this program:
```
#[macro_use]
extern crate mirai_annotations;

fn safe_div(x: u64, y: u64) -> Option<u64> {
    if y != 0 {
        Some(x / y)
    } else {
        None
    }
}

pub fn main() {
    let x = abstract_value!(2u64);
    assume!(x > 0);
    assume!(x <= std::u64::MAX / 2); // avoid overflow
    let a = safe_div(2 * x, x);
    match a {
        Some(x) => verify!(x == 2),
        None => verify!(false),
    };
    let b = safe_div(x, 0);
    match b {
        Some(_x) => verify!(false),
        None => verify!(true),
    };
}
```

## Expected Behavior

The program should verify, and yet MIRAI reports a bug.

## Environment

MIRAI v1.0.5rustc 1.42.0-nightly (9ed29b6ff 2020-01-29)

**Comment by hermanventer** [comment]
I submit to you that the expression `false` is provably false. :-)

That may not seem like something the prover should comment on, but it is arguably bad style. Better would be to write `verify_unreachable!()`.

Best of all would be to write idiomatic Rust:
```
#[macro_use]
extern crate mirai_annotations;

fn safe_div(x: u64, y: u64) -> Option<u64> {
    if y != 0 {
        Some(x / y)
    } else {
        None
    }
}

pub fn main() {
    let x = abstract_value!(2u64);
    assume!(x > 0);
    assume!(x <= std::u64::MAX / 2); // avoid overflow
    let a = safe_div(2 * x, x);
    verify!(a.unwrap() == 2);
    let b = safe_div(x, 0);
    verify!(b.is_none());
}
```

**Comment by zvonimir** [comment]
Wait, just to clarify this. If I write `verify!(false)` anywhere in the code, MIRAI will always report that as a bug even though it might not be reachable?
Is that what is going on there?
I am just trying to understand the algorithm better.

**Comment by hermanventer** [comment]
Yes, `false` is a bit of a special case but if it were an expression and always evaluates to false, that is likely unintentional.

In your case it is clearly intentional, but it is not quite the best way of documenting what you are trying to say, namely that this statement is never reachable. The preferred way to doing that is to be explicit can call `verify_unreachble!`.

Of course, you are trying to use a minimal set of annotations, so that is probably not an option for you. You can, however, easily get the same effect by using methods such as unwrap.

Given that, I'd like to stick with this restriction until it becomes clearly untenable.

**Comment by zvonimir** [comment]
I see. So what is then the semantics of `verify!`?

I thought its semantics matched what I would expect of `assert!`, but now I see that is not quite the case - since assert does not trigger if it is not reachable. It would be great to more precisely document what the semantics of `verify!` is for future users.

**Comment by hermanventer** [comment]
The doc comment for verify! is as follows:

```
/// Equivalent to a no op when used with an unmodified Rust compiler.
/// When compiled with MIRAI, this causes MIRAI to check the condition and
/// emit a diagnostic unless it can prove it to be true.
```

The actual behavior is a bit more complicated, but the comment is close enough in my opinion.
