### ISSUE TITLE
Incorrect unreachability results when preconditions contain model fields

### ISSUE THREAD

**Issue by stonebuddha** [facebookexperimental/MIRAI#577]
## Issue

MIRAI reports weird unreachability results when function preconditions involve model fields. The cause might be that the method `CallVisitor::transfer_and_refine_normal_return_state` might refine values under an incomplete environment, in a way that unknown model fields are incorrectly resolved to their default values.

## Steps to Reproduce

Run MIRAI on the following code:

``` rust
struct Foo {}

fn func(foo: &Foo) {
    precondition!(get_model_field!(foo, value, 0) == 99991);
}

pub fn main() {
    let foo = Foo {};
    set_model_field!(&foo, value, 99991);
    func(&foo);
    verify!(get_model_field!(&foo, value, 0) == 99991);
}
```

## Expected Behavior

The program contains no bugs, so MIRAI is supposed to report no errors.

## Actual Results

MIRAI reports an unreachable statement:

```
warning: this is unreachable, mark it as such by using the verify_unreachable! macro
   --> src/main.rs:455:5
    |
455 |     verify!(get_model_field!(&foo, value, 0) == 99991);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
```

## Environment

rustc 1.46.0-nightly (2753fab7c 2020-07-05)

**Comment by hermanventer** [comment]
What is happening here is that the post condition is refined in an incomplete environment. This is obviously wrong, but there is a reason why this happens at all: Post conditions are more interesting to the SMT solver if constraints that are known to be true are not simplified. The simplistic technique for achieving this breaks down in the face of model fields. I'll come up with something better.
