### ISSUE TITLE
Incorrect unreachability results on for-in loops

### ISSUE THREAD

**Issue by stonebuddha** [facebookexperimental/MIRAI#590]
## Issue

MIRAI reports weird unreachability results when analyzing for-in loops. It seems that for-in loops invoke some intrinsics (such as `std::intrinsics::wrapping_add`) that are not handled by MIRAI.

## Steps to Reproduce

Run MIRAI on the following code:

``` rust
pub fn main() {
    for i in 0..100 {
        verify!(i < 100);
    }
}
```

## Expected Behavior

The program contains no bugs, so MIRAI is supposed to report no errors.

## Actual Results

MIRAI reports an unreachable statement:

```
warning: this is unreachable, mark it as such by using the verify_unreachable! macro
   --> src/main.rs:533:9
    |
533 |         verify!(i < 100);
    |         ^^^^^^^^^^^^^^^^^
    |
```

## Environment

rustc 1.46.0-nightly (2753fab7c 2020-07-05)

**Comment by stonebuddha** [comment]
The issue seems to be partly fixed: Now MIRAI does not report unreachability results, but report a false positive:
```
warning: possible false verification condition
    --> src/main.rs:1009:9
     |
1009 |         verify!(i < 100);
     |         ^^^^^^^^^^^^^^^^^
     |
```

**Comment by hermanventer** [comment]
This has been fixed.
