### ISSUE TITLE
Incomplete summary of side effects

### ISSUE THREAD

**Issue by stonebuddha** [facebookexperimental/MIRAI#597]
## Issue

MIRAI seems to produce an incomplete summary of side effects, when the summarized function mutates a path rooted by a parameter X, and then copies the parameter X to another parameter Y.

## Steps to Reproduce

Run MIRAI on the following code:
``` rust
fn mutate_and_then_copy(dest: &mut (i32, i32), src: &mut (i32, i32)) {
    src.1 = 789;
    *dest = *src;
}

pub fn main() {
    let mut a = (123, 456);
    let mut b = (456, 123);
    mutate_and_then_copy(&mut a, &mut b);
    verify!(b.0 == 456 && b.1 == 789);
    verify!(a.0 == 456 && a.1 == 789);
}
```

## Expected Behavior

The program contains no bugs, so MIRAI is supposed to report no errors.

## Actual Results

MIRAI reports a provably false verification condition:
```
error: provably false verification condition
   --> src/main.rs:614:5
    |
614 |     verify!(a.0 == 456 && a.1 == 789);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
```

## Environment

rustc 1.46.0-nightly (2753fab7c 2020-07-05)

**Comment by stonebuddha** [comment]
https://github.com/facebookexperimental/MIRAI/blob/de0abe068598fa18922a91875b4eafd19229c7b8/checker/src/body_visitor.rs#L1852-L1854
The logic of `non_patterned_copy_or_move_elements` might ignore some children paths, if the environment tracks some, but not all of them.

I'm not sure if there exists an easy fix. In general, we might need abstract qualified paths, e.g., `a.b.*` represents the set of possible paths rooted at `a.b`. Here's [a related paper](https://www.bodden.de/pubs/lsb+15access-path.pdf) about access-path abstractions.

**Comment by hermanventer** [comment]
a.b.* is just another way of writing a.b.deref.
