### ISSUE TITLE
Consider merging / reusing infer

### ISSUE THREAD

**Issue by LifeIsStrange** [facebookexperimental/MIRAI#599]
Facebook already own, as you might be aware, a "state of the art" polyglot static analyzer:
https://github.com/facebook/infer

MIRAI seems interesting and Rust critically needs a decent static analyzer but wouldn't it be possible to merge with infer?

Also, do you consider leveraging 
https://github.com/rust-lang/chalk for increasing the expressive power of your analysises?

**Comment by hermanventer** [comment]
As far as chalk is concerned, MIRAI uses rust compiler APIs to resolve trait methods. I am confident that this is the right approach and if the current rustc nightly does not already leverage chalk, it will as soon as it makes sense.

The first question is not simple. We are, of course, aware of Infer and know the team members. It is certainly conceivable that a Rust front-end for Infer can be written and perhaps this will happen one day. When it does, I'll be delighted and do what I can to help it along.

I do not, however, expect that this will be a particularly easy thing to do and do not foresee it becoming a priority for the Infer team any time soon either.

Meanwhile, there are a lot of benefits to be had from a relatively small and fast analyzer that plugs directly into the Rust compiler and fits seamlessly into Cargo and the way people build Rust outside of Facebook. Given the limited resources available and the need for short term results, it is my considered opinion that MIRAI is currently the best way to get a decent static analyzer for Rust.

I wont be sad if someone else gets there first or gets there better, but MIRAI is where I'm placing my personal bet.

**Comment by LifeIsStrange** [comment]
Sound answer, thanks!
