### ISSUE TITLE
Weak updates during refinements

### ISSUE THREAD

**Issue by stonebuddha** [facebookexperimental/MIRAI#603]
## Issue

MIRAI loses track of some side effects when the callee performs weak updates.

## Steps to Reproduce

Run MIRAI on the following code:
``` rust
fn test(a: &mut [i32; 4], i: usize) {
    a[i] = 666;
}

pub fn main() {
    let mut v = [1, 2, 3, 4];
    let i = abstract_value!(1);
    assume!(i < 4);
    test(&mut v, i);
    verify!(v[1] == 666);
}
```

## Expected Behavior

The verification condition can be either true or false, so MIRAI is supposed to report a possible false verification condition.

## Actual Results

MIRAI reports a provably false verification condition:
```
error: provably false verification condition
   --> src/main.rs:648:5
    |
648 |     verify!(v[1] == 666);
    |     ^^^^^^^^^^^^^^^^^^^^^
    |
```

## Environment

rustc 1.46.0-nightly (2753fab7c 2020-07-05)

**Comment by hermanventer** [comment]
It seems perfectly reasonable to claim that the verification condition is provably false. On the other hand, if you change 666 to 2, the verification is erroneously accepted as true, so there is bug here.
