### ISSUE TITLE
Replace debug! calls with trace! calls.

### ISSUE THREAD

**Issue by hermanventer** [facebookexperimental/MIRAI#64]
## Issue

Trace output can be overwhelming so I often want to turn that off. On the other hand, since debugging support for Rust is pretty much non existent, I often need to insert some kind of print statement in the code while debugging. This is covered by the distinction between trace! and debug!, but unfortunately the code I looked at early on only ever used debug! and I just followed that.

**Comment by hermanventer** [comment]
See https://crates.io/crates/log-derive.

**Comment by ortem** [comment]
Hi @hermanventer! I've just heard about MIRAI. The project is very exciting and I hope it really will ever be a part of IntelliJ Rust and RLS code analysis! However, while reading the documentation I was surprised to see that CLion doesn't support debugging MIRAI ([1](https://github.com/facebookexperimental/MIRAI/blob/master/documentation/DeveloperGuide.md#debugging) and [2](https://github.com/facebookexperimental/MIRAI/blob/master/documentation/DebuggingRustc.md)).

I've just tried it out and seems like it works fine:
<img width="992" alt="Screenshot 2019-03-30 at 12 21 02" src="https://user-images.githubusercontent.com/4854600/55274221-2567e680-52e7-11e9-9bed-5b5160a7b89a.png">

All I have to do is to provide the `DYLD_LIBRARY_PATH` as specified: 
<img width="1185" alt="Screenshot 2019-03-30 at 12 35 29" src="https://user-images.githubusercontent.com/4854600/55274333-5399f600-52e8-11e9-82c1-bac7cd62c589.png">

Also,
> debugging support for Rust is pretty much non existent

I'm sorry to hear that. I'm working on new lldb formatters for Rust; in CLion, they are enabled by default and configurable via `Preferences | Build, Execution, Deployment | Debugger | Data Views | Rust`. I hope debugging support gets better, though there is no `Evaluate expression` for Rust yet. So I really want to know if something related to debugging frontend doesn't work properly or if you have some ideas to improve it (at frontend level, like formatters). If so, you can open an issue [here](https://github.com/intellij-rust/intellij-rust/issues).
