### ISSUE TITLE
Failure to analyze a crate with MIRAI

### ISSUE THREAD

**Issue by a-malyshev** [facebookexperimental/MIRAI#672]
## Issue

Not able to perform analysis of **libra-crypto** crate with **MIRAI**.
Executing `RUSTC_WRAPPER=mirai cargo build` finishes with a compilation error.

 `unicode-xid` that transitively downloaded during the compilation causes the issue. But I assume other libraries might lead to a similar error. 

Am I missing something?

## Steps to Reproduce

```
rustup override set nightly-2020-10-06
cd ~/MIRAI
./setup.sh
cargo clean
cargo uninstall mirai
cargo install --debug --path ./checker
```

```
cd ~
cargo new some_crate
cd some_crate
rustup override set nightly-2020-10-06
echo 'unicode-xid = "0.2.1"' >> Cargo.toml
RUSTC_WRAPPER=~/MIRAI/target/debug/mirai cargo check
```

In order to make sure that is not a problem for my local machine's environment, I repeated these steps on `VM` with `fedora`, but the result is the same.
Also, tried to use **MIRAI** built with the `nightly-2020-09-10` version.
Building the crate with the original compiler (`cargo build`) works fine.

## Expected Behavior

successful build

## Actual Results

``` 
error: could not compile `unicode-xid`

Caused by:
process didn't exit successfully: `mirai rustc  --crate-name unicode_xid /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-xid-0.2.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' -C metadata=b13daac5d45350a3 -C extra-filename=-b13daac5d45350a3 --out-dir /home/alex/libra/target/debug/deps -L dependency=/home/alex/libra/target/debug/deps --cap-lints allow` (signal: 15, SIGTERM: termination signal)
```

## Environment

`rustc version` is `nightly-2020-10-06`
Ubuntu 18.04 and Fedora 32

**Comment by hermanventer** [comment]
You'll have better results if you try to build ONLY libra-crypto with MIRAI. I.e. first build everything with 
`RUSTFLAGS="-Z always_encode_mir" cargo build -p libra-crypto`

Then `touch crypto/crypto/src/lib.rs`

Then run MIRAI with `RUSTC_WRAPPER=mirai cargo build -p libra-crypto`

**Comment by a-malyshev** [comment]
This causes `error: could not compile 'libc'. 
Running with the flag `RUST_BACKTRACE=full`  is not really helpful. [full output](https://gist.github.com/a-malyshev/9b4e9f445ddd46ee2786fbe7f865a055)

I had the same error before and then decided to find a minimal crate that causes this issue. That's how I found that  `unicode-xid` is the cause.

**Comment by hermanventer** [comment]
The second build is not incremental, probably because the compiler flags have changed.

**Comment by a-malyshev** [comment]
yes, passing the flag `RUSTFLAGS="-Z always_encode_mir"` for the second build makes a difference (or building the crate with not including this flag for the first build, also works) 

I assume that in your case it works as you described in a couple of messages above(and it also described in **Using MIRAI** section in the README). I wonder why cargo rebuilds the whole crate in my case? 
but anyway thank you for the help!

**Comment by hermanventer** [comment]
It works for me because I have set RUSTFLAGS="-Z always_encode_mir" in my environment, hence it gets passed to the rustc compiler during the initial build as well as during the incremental build. The README was written on the assumption that this is what is meant by set RUSTFLAGS="-Z always_encode_mir", but I see now that this is hardly a clear instruction.
