### ISSUE TITLE
pub fn main() vs. fn main()

### ISSUE THREAD

**Issue by steveyko** [facebookexperimental/MIRAI#947]
## Issue

Unlike ``pub fn main()``, ``fn main()`` doesn't seem to be a default entry point. ``cargo new`` creates ``fn main()``. I was wondering if there's a particular reason for that.

## Steps to Reproduce

Create a new project with cargo then run MIRAI.

## Expected Behavior

MIRAI analyzing the program using ``fn main()`` as the entry point.

## Actual Results

No analysis done.

## Environment

nightly-2021-07-29

**Comment by hermanventer** [comment]
No reason. This needs fixing.
